# Dockerfile.test

FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
COPY tests/ ./tests/
COPY src/ ./src/

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest

CMD ["pytest", "tests/"]